gem 'redmine_crm'
gem 'google-api-client'
gem 'google_drive'
gem 'sidekiq'
gem 'wannabe_bool', '~> 0.7.1'
gem 'psych', '~> 3.3'
gem 'docx'
gem 'sprockets'
gem 'deface'
gem 'libreconv', '~> 0.9.5'
gem 'msworddoc-extractor'
gem 'yomu'
gem 'safe_regexp'
gem 'vuejs'
